name: Lint

on:
    pull_request:
    push:
        branches:
            - "*-dev*"
            - dev
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: lts/*
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Run Lint Check
              run: npm run lint:ci
