name: Tests

on: [pull_request]

jobs:
    "test":
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  ssh-key: ${{ secrets.SSH_KEY }}
                  submodules: "recursive"

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                node-version: lts/*
                cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run test:ci
    
    "meteor-test":
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  ssh-key: ${{ secrets.SSH_KEY }}
                  submodules: "recursive"

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                node-version: lts/*
                cache: npm

            - name: Install Meteor
              run: |
                  curl https://install.meteor.com/ | sh

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run meteor:test:ci
